### ISSUE TITLE
Patrolium Boiler

### ISSUE THREAD

**Issue by MHarrisonBrz** [oni-guides/oni-guides#4]
Hi, 
I'm currently building the petroleum boiler and currently filling the left side with water.  When I go to deconstructing the liquid valve how do I remove the debris from the bottom of the boiler room?  My understanding is that when the hot igneous rock touches that any other debris it will assume the heat of the debris?
From what I'm seeing is that this was built in SANDBOX mode and not built by real dupes.
If this is true then it should be removed as a build guide so people that are playing the "real" game don't waste their time.

**Comment by kyldvs** [comment]
I ensure that all of my builds can be built in real games by real dupes. I even include a section that explains how to build everything to help make things easier for people. I didn't call out exactly how to prevent the debris from the liquid valve removal, you should close off the water section before deconstructing the valve so nothing will fall in.
